POST http://localhost:3500/signin
Content-Type: application/json

{
    "email": "boris16@boris.com",
    "password": "boris1",
    "username":"Boris"
}
###
POST http://localhost:3500/login
Content-Type: application/json

{
    "email": "boris13@boris.com",
    "password": "boris1"
}


###
POST http://localhost:3500/logout

###
GET  http://localhost:3500/user