POST http://localhost:3500/signin
Content-Type: application/json

{
    "email": "boris11@boris.com",
    "password": "boris9",
    "username":"Boris"
}
###
POST http://localhost:3500/login
Content-Type: application/json

{
    "email": "boris11@boris.com",
    "password": "boris9"
}


###
POST http://localhost:3500/logout
